### ISSUE TITLE
Missing docs: point_cloud

### ISSUE THREAD

**Issue by catid** [dylanebert/gaussian-viewer#1]
Got the software running on an Ubuntu Linux server with RTX 4090 and installed the example data as described in the README but it produces this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'models/bicycle/point_cloud/iteration_30000/point_cloud.ply'
```

Looks like there are some missing steps in the documentation to get it working?

**Comment by dylanebert** [comment]
You can find it in the Downloading Models section of the README :)
https://github.com/dylanebert/gaussian-viewer#downloading-models

**Comment by catid** [comment]
@dylanebert I think you'll find if you do a fresh checkout and follow the instructions you linked that these files are missing

**Comment by dylanebert** [comment]
Sorry you're right, I pointed to the wrong data to download, I will fix this

**Comment by dylanebert** [comment]
Should be fixed now!

**Comment by catid** [comment]
Thanks mate!
