### ISSUE TITLE
Aren't we encoding then decoding needlessly? 

### ISSUE THREAD

**Issue by bc-anam** [dylanebert/gaussian-viewer#3]
It's likely I don't understand the code properly but it seems like we first encode to h264 on the GPU in `render.py` then decode from h264 in `parse_frames(...)` in `main.py`? 

If so, isn't this a needless roundtrip?

**Comment by dylanebert** [comment]
`render.py` encodes the images to H264 on GPU

`parse_frames` packetizes the H264 data, it doesn't convert it back to images
